FROM centos
RUN yum install -y httpd unzip
Label Maintainer=Badal
ENV HTML beginner-html-site-styled
WORKDIR /var/www/html
ADD https://github.com/mdn/$HTML/archive/gh-pages.zip ./code.zip
RUN unzip code.zip && mv ./$HTML-gh-pages/* . && echo $HTML > ./env.html
RUN useradd application && chown -R application:application /var/www/html
USER application
RUN rm -rf code.zip $HTML-gh-pages
CMD apachectl -DFOREGROUND
