FROM centos
ARG user
ARG httpd_package
RUN yum -y install $httpd_package unzip
LABEL MAINTAINER=BADAL
ENV HTML beginner-html-site-styled
WORKDIR /var/www/html/
ADD https://github.com/mdn/$HTML/archive/gh-pages.zip ./code.zip
RUN unzip code.zip && mv $HTML-gh-pages/* . && echo $HTML > ./env.html
RUN useradd $user && chown -R $user:$user .
USER $user
RUN rm -rf code.zip $HTML-gh-pages/
USER root
CMD apachectl -DFOREGROUND

==================================================================
1) Here noting points ARG httpd_package if you give httpd-package then container unable to understand n give error
2) . means this path /var/www/html/ & we use . for instructions like COPY & ADD or to define this path /var/www/html/
3) as we defined WORKDIR /var/www/html/
means we are executing commands in this path
docker build -t apache-with-code:v4 -f Dockerfile-cmd --build-arg user=badal --build-arg httpd_package=httpd .

docker run -d -p 9090:80 --name apache11 apache-with-code:v4
