FROM centos
ARG user=application
RUN yum install -y httpd unzip
Label Maintainer=Badal
ENV HTML beginner-html-site-styled
WORKDIR /var/www/html
ADD https://github.com/mdn/$HTML/archive/gh-pages.zip ./code.zip
RUN unzip code.zip && mv ./$HTML-gh-pages/* . && echo $HTML > ./env.html
RUN useradd $user && chown -R $user:$user /var/www/html
USER $user
RUN rm -rf code.zip $HTML-gh-pages/
USER root
CMD apachectl -DFOREGROUND
